project:
  type: website

website:
  title: "By me"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: curriculo.qmd
        text: Curriculum Vitae
      - href: project.qmd
        text: Projectos a desenvolver
      - href: contact.qmd
        text: Contacto
      

format:
  html:
    theme: cosmo
    css: styles/custom.css
    toc: true

editor: visual

